PL-397 Add microseconds to the database name to avoid naming clashes
Homeservenow/aurora-sequelize-pg pull request #9
Opened 2021-02-15 14:48 UTC by AlexHayton

https://homeservenow.atlassian.net/browse/PL-397

## Brief description of what's changing
- [ ] Add microseconds to the database name in a backwards-compatible way
- [ ] Improve test coverage

## Brief description of why it's changed
To avoid duplicate DB name errors when running lots of tests at around the same time.

2021-02-15 15:19 UTC, mthomasuk approved these changes
🎉

2021-02-15 15:54 UTC, alecdotico requested changes

2021-02-15 15:54 UTC, alecdotico commented on src/sequelize.init.ts
> +let instance: Sequelize | null;
This was explicitly implemented as OO to state the singleton pattern. This functional approach might produce [the same](https://stackoverflow.com/a/47298363/2586601) output as the OO approach, but I am not entirely sure, would have to investigate further into Javascript import evaluation. 
Anyway, for future readers it won't be as clear that this is a singleton pattern

2021-02-15 15:54 UTC, alecdotico commented on src/testSuite/testHelpers.ts
> +  const tempDbName = `${existingDbName}_${microseconds()}_test${dateToDbSuffix(new Date())}`;
microseconds should be part of the timestamp suffix, inside the `dateToDbSuffix` function. For instance, `jobs_test2021021515652001`. Thus, all temporary databases can be sorted alphabetically and deleted by timestamp.

2021-02-15 15:54 UTC, alecdotico commented on src/testSuite/testHelpers.ts
> +  const tempDbName = `${existingDbName}_${microseconds()}_test${dateToDbSuffix(new Date())}`;
this change also requires to update the `deleteOldTestDatabases` function, `'%_test[0-9]{15,18}'`

2021-02-15 16:38 UTC, AlexHayton commented on src/sequelize.init.ts
> +let instance: Sequelize | null;
I actually found your one harder to read! I guess I'm just used to doing singletons this way... @mthomasuk casting vote?

2021-02-15 16:38 UTC, AlexHayton commented on src/testSuite/testHelpers.ts
> +  const tempDbName = `${existingDbName}_${microseconds()}_test${dateToDbSuffix(new Date())}`;
ok I'll refactor this

2021-02-15 17:08 UTC, AlexHayton commented on src/testSuite/testHelpers.ts
> +  const tempDbName = `${existingDbName}_${microseconds()}_test${dateToDbSuffix(new Date())}`;
Done. @alecdotico please can you take another look?

2021-02-16 08:50 UTC, alecdotico approved these changes

2021-02-16 08:50 UTC, alecdotico commented on src/testSuite/testHelpers.ts
> +  const tempDbName = `${existingDbName}_test${dateToDbSuffix(new Date())}${microseconds()}`;
Looking better, but I still think that the `microseconds` function should be an internal of the `dateToDbSuffix` function. See it as a random seed added to the end of the suffix.

2021-02-17 09:06 UTC, AlexHayton commented on src/testSuite/testHelpers.ts
> +  const tempDbName = `${existingDbName}_test${dateToDbSuffix(new Date())}${microseconds()}`;
Alright! :)

2021-02-17 09:21 UTC, mthomasuk commented on src/sequelize.init.ts
> +let instance: Sequelize | null;
it's harder to read but yeah, who fucking knows how JS is going to handle this - seems to be working in the current format, maybe leave it? unless someone wants to go full metal jacket with this

2021-02-17 12:18 UTC, merged